name: adyen_api
description: Adyen API library for Dart.
version: 0.0.1
repository: https://github.com/Lutra-Fs/adyen_api_dart
issue_tracker: https://github.com/Lutra-Fs/adyen_api_dart/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  # web: Partially supported - Terminal Local API requires dart:io

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  crypto: ^3.0.3
  dio: ^5.7.0
  one_of: ^1.5.0
  one_of_serializer: ^1.5.0
  pointycastle: ^3.9.1

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  http_mock_adapter: ^0.6.1
  lints: ^6.0.0
  test: ^1.25.6
